# docker-compose nginx+nextjs+fastapi
version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/ # default config
      - ./nginx/certs/:/etc/nginx/certs/ # certificate files for https
    depends_on:
      - web
  web:
    build: ./next-app
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./next-app/:/usr/app/
      # - ./next-app/packages.json:/usr/app/packages.json
      - dependencies:/usr/app/node_modules
  fastapi:
    build: ./fastapi-app
    container_name: fastapi
    ports: 
      - "8000:8000"
    volumes:
      - ./fastapi-app/app/:/code/app/
      - ./fastapi-app/requirements.txt:/code/requirements.txt
      - fastapi_packages:/usr/local/lib/python3.10/site-packages
  install: # service for install additional web service's dependencies
    image: pe-dx_web # image web services (*project dir.*_web)
    container_name: install
    depends_on:
      - web
    volumes:
      - ./next-app/:/usr/app/
      - dependencies:/usr/app/node_modules
    working_dir: /usr/app
    command: sh -c "yarn && touch index.js"
  install_fastapi: # service for install additional fastapi's packages
    image: pe-dx_fastapi # image fastapi
    container_name: fastapi_install
    depends_on:
      - fastapi
    volumes:
      - ./fastapi-app/requirements.txt:/code/requirements.txt
      - fastapi_packages:/usr/local/lib/python3.10/site-packages
    working_dir: /code
    command: sh -c "pip install --no-cache-dir -r /code/requirements.txt"
volumes:
  dependencies:
  fastapi_packages: