import "animate.css";
import { useEffect, useState } from "react";
import type { AppProps } from "next/app";
import Head from "next/head";
import { appWithTranslation } from "next-i18next";
import Layout from "@/components/layout/layout";
import "@/styles/app.scss";
import store from "@/app/store";
import { Provider } from "react-redux";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <div className="app-main">
        <Head>
          <title>PE DX Apps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pe-dx-logo.ico" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </div>
    </Provider>
  );
}

export default appWithTranslation(MyApp);
