import axios from "axios";
import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const LanguageSelector = () => {
  const router = useRouter();
  return (
    <div className="language-selector">
      {router.locales?.map((locale, index) => {
        if (router.locale !== locale) {
          return (
            <Link href={"/"} locale={locale} key={index}>
              {locale.toLowerCase()}
            </Link>
          );
        }
      })}
    </div>
  );
};

const Home: NextPage = () => {
  const { t } = useTranslation();
  const router = useRouter();

  function getData() {
    console.log("get data");
    axios
      .get("http://localhost:8000/")
      .then((res) => {
        console.log(res.data);
      })
      .catch((err) => console.log(err));
  }

  return (
    <div className="main-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <LanguageSelector />
        <h1>
          {t("common:welcome")} <b>PE application</b>
        </h1>
        <div className="link-group">
          <Link href={"/camera"}>Camera</Link>
        </div>
      </main>

      <footer className="footer">
        <p>
          Powered by <b>PE BPK</b>
        </p>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  let loc = "";
  if (locale) {
    loc = locale;
  }
  return {
    props: {
      ...(await serverSideTranslations(loc, ["common"])),
    },
  };
};

export default Home;
