import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const LinkGroup = () => {
  return (
    <div className="link-group">
      <Link href={"/5m1e"}>
        <p>
          <b>5M1E</b> Report
        </p>
      </Link>
      <Link href={"/dea"}>
        <p>
          <b>D</b>ocument <b>E</b>asy <b>A</b>ccess
        </p>
      </Link>
    </div>
  );
};

const Home: NextPage = () => {
  const { t } = useTranslation();

  return (
    <div className="home">
      <Head>
        <title>PE DX Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pe-dx-logo.ico" />
      </Head>

      <main className="home-content">
        <h1>
          {t("common:welcome")} <b>PE application</b>
        </h1>
        <LinkGroup />
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  let loc = "";
  if (locale) {
    loc = locale;
  }
  return {
    props: {
      ...(await serverSideTranslations(loc, ["common"])),
    },
  };
};

export default Home;
